### ISSUE TITLE
Implement CSS Color 4 gamut mapping

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#154]
Currently, gamut mapping tries to allow any coordinate in any color space to be reduced (including nonsensical ones like hue) and uses deltaE 2000 as a color distance metric.

- [x] Implement [proposed improved CSS color 4 gamut mapping](https://github.com/w3c/csswg-drafts/issues/7135#issuecomment-1066121795) in [a codepen](https://codepen.io/svgeesus/pen/GRxJRKz?editors=0010) (far end of JND MINDE)
- [x] Investigate [odd results with imaginary colors](https://github.com/w3c/csswg-drafts/issues/7071)
- [ ] Add to color.js codebase
- [ ] Make it the default GMA

See also [this codepen](https://colorjs.io/notebook/?storage=https%3A%2F%2Fgist.github.com%2Fsvgeesus%2F1ae7f34724b0d5e7ca99f217d52446d5) and [this demo](https://danburzo.ro/demos/color/gamut-mapping.html)

**Comment by svgeesus** [comment]
Does not just affect GM single colors, but also affects smoothness of gradients, see [this awful example](https://github.com/w3c/csswg-drafts/issues/7071#issuecomment-1049417689)

**Comment by svgeesus** [comment]
On `lab(50% -127 -127)` I get starting oklch of 
`[ 0.42226189321340196, 1.9540778145796625, 191.20237227483153 ]`
and after GM I get
`[ 0.43100803800138154, 0.0741924017206513, 191.0338159551419 ]`

So the chroma is vastly reduced but the hue is very similar.

**Comment by svgeesus** [comment]
Exploring the CIE Lab L=50 plane over  a,b = -125 to +125 I am struck by the OKLab a value in the -125,-125 corner:

lab(50% 125 125)   =  oklab(60.58% 0.357 0.152)
lab(50% -125 125)  =  oklab(53.41% -0.32 0.194)
lab(50% -125 -125) =  oklab(42.27% **-1.9** -0.37)
lab(50% 125 -125)  =  oklab(65.4% 0.257 -0.35)

**Comment by svgeesus** [comment]
So exploring the CIE a,b plane gives odd results if the GMA is using OKLCH

![image](https://user-images.githubusercontent.com/2506926/177008783-0e9cacc4-b026-4a65-aeb2-bc6a092935e7.png)


but equally, exploring the OKLab ab plane while mapping in CIE LCH is odd too

![image](https://user-images.githubusercontent.com/2506926/177008860-00825402-a342-4aa4-98fb-c584a0833a81.png)

**Comment by svgeesus** [comment]
_(TIL that screenshots of Canvas elements on my WCG screen look nothing like the actual screen)_

**Comment by svgeesus** [comment]
Here exploring OKLab a,b we see mapping in CIELCH gives a patch of solid color in the a positive, b positive corner (bottom right)

![image](https://user-images.githubusercontent.com/2506926/177009230-38803caa-8370-4c95-bb75-f17128f19ea7.png)

**Comment by svgeesus** [comment]
Live versions:

 - [CIE Lab explorer](https://svgees.us/Color/CIEexplorer.html)
 - [OKLab explorer](https://svgees.us/Color/okexplorer.html)

**Comment by jamesnw** [comment]
@svgeesus - We are looking to use Color.js to implement CSS Color 4 logic (conversions, gamut, etc) for Sass in the `node-embedded-host`, and gamut mapping is one piece that is currently missing. Is there anything blocking this algorithm from being used in Color.js? (Perhaps waiting for clarity on https://github.com/w3c/csswg-drafts/issues/9449 or other outstanding issues?) 

If there isn't anything blocking, are there parts that we could help implement here in Color.js?

**Comment by LeaVerou** [comment]
@jamesnw exciting! Would love to support you folks in this.
AFAIK the only blocker is our lack of time: both @svgeesus and I are spread very thin. So yeah, we'd **love** help from you folks! Happy to assist with any questions about the codebase, architecture, API etc.

**Comment by jamesnw** [comment]
@LeaVerou Great! I have a draft PR at https://github.com/LeaVerou/color.js/pull/344. I have a few questions there, and am open to your thoughts on documentation and how best to incorporate this change. Thanks!

**Comment by svgeesus** [comment]
Closed by https://github.com/color-js/color.js/pull/352
