### ISSUE TITLE
Color spaces that are not present in CSS should serialize with <dashed-ident> color space id in `color()`

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#178]
E.g. hsv should serialize as `color(--hsv)`, not `color(hsv)`.

**Comment by svgeesus** [comment]
Yes, although [per CSS Color 5](https://www.w3.org/TR/css-color-5/#custom-color) custom color spaces are only supported if backed by an `@color-profile`

**Comment by svgeesus** [comment]
But it does make it clearer

**Comment by LeaVerou** [comment]
This was resolved in v0.5.0.
