### ISSUE TITLE
OKHSV and OKHSL

### ISSUE THREAD

**Issue by mattdesl** [color-js/color.js#312]
It would be nice to have support for OKHSV and OKHSL, I find OKLCH challenging to work for color picking.

I have written basic support for OKHSV and OKHSL color spaces within color.js, you can see it here:

https://github.com/mattdesl/workshop-generative-color/blob/f5a26247fac7e6dc617f05fd23886a3bba6b5d4b/lib/color.js#L10-L81

and using the color conversion tools here:

https://github.com/mattdesl/workshop-generative-color/blob/f5a26247fac7e6dc617f05fd23886a3bba6b5d4b/lib/oklab.js

These conversions are only slightly modified and stripped down from Björn's color picker code, see here:

https://github.com/bottosson/bottosson.github.io/blob/master/misc/colorpicker/colorconversion.js (MIT license, as far as I can see)

**Comment by LeaVerou** [comment]
Hi there,
We’d happily merge a PR on this. Do you think you might be able to send one?
