### ISSUE TITLE
NaN hue values

### ISSUE THREAD

**Issue by sidewayss** [color-js/color.js#328]
Clearly related to this issue/question: https://github.com/LeaVerou/color.js/issues/56

But IMO this is a bug as it relates to the numeric values in the `hsl`, `hwb`, `lch`, and `oklch` properties of `Color`, and I wanted to express it in a more concise form than issue 56.  See this codepen for an illustration: https://codepen.io/sidewayss/pen/VwqWoGx

For monochrome rgb values, the conversion to hue results in `NaN` instead of zero in the numeric arrays represented by the properties mentioned above.  I see that in the string properties for these color spaces `NaN` is replaced by the keyword `none`, which is equivalent to zero, but for the numeric properties `NaN` is awkward and essentially incorrect.

**Comment by facelessuser** [comment]
> For monochrome rgb values, the conversion to hue results in NaN instead of zero in the numeric arrays represented by the properties mentioned above. I see that in the string properties for these color spaces NaN is replaced by the keyword none, which is equivalent to zero, but for the numeric properties NaN is awkward and essentially incorrect.

This is actually quite appropriate. A monochromatic color has no hue; therefore, one cannot be provided on convert. It should be noted that while CSS may treat `NaN` or `none` as `0` when it feels it absolutely needs a number, an undefined value is not equivalent to `0`, it is simply the resolution that has been chosen.

**Comment by sidewayss** [comment]
It's only inappropriate if you're requesting an array of 3 numbers as your converted value.  That's my use case.  You can't scale or adjust `NaN` in any way for animation, while zero is a viable number.  Yes, I can and now do convert `NaN` to zero, but it's awkward and seems wrong to me.

**Comment by facelessuser** [comment]
It may be appropriate to expose some way to grab coordinates with undefined values normalized.

**Comment by sidewayss** [comment]
> It may be appropriate to expose some way to grab coordinates with undefined values normalized.

I'm new to color spaces and new to colorjs, but it seems to me that the place to do it is these existing properties that expose an array of numbers.

**Comment by sidewayss** [comment]
I see [here](https://github.com/LeaVerou/color.js/blob/f505c1b5230e1eabf5893f6a8eefb335936e55e0/src/spaces/hsl.js#L30) that the `NaN` is initial value for HSL/HWB hue, and [here](https://github.com/LeaVerou/color.js/blob/f505c1b5230e1eabf5893f6a8eefb335936e55e0/src/spaces/lch.js#L32) and [here](https://github.com/LeaVerou/color.js/blob/f505c1b5230e1eabf5893f6a8eefb335936e55e0/src/spaces/oklch.js#L33) that lch and oklch set it explicitly. I can see how you are talking about another set of properties, especially if these are used internally.  Oh well, I'm probably barking up the wrong tree here, as no one else has noticed or cared enough to mention it.
