### ISSUE TITLE
JSON serialization of NaN

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#329]
The parse tests for none are failing because NaN isn't valid JSON.

![image](https://github.com/LeaVerou/color.js/assets/65072/87524755-a04d-4bdc-894b-4c1c8aa0c456)

I can think of a number of different solutions:

1. change the tests to expect null
2. serialize NaN as "none"
3. serialize NaN as 0
4. something else

I can create a PR, just need to know what the appropriate fix should be.

**Comment by svgeesus** [comment]
@LeaVerou we had discussed this and were between the first two:

> 1. change the tests to expect `null`
> 2. serialize NaN as "none"

I think that if serialising coords to JSON we should go with `null` and if serializing a color to CSS then we want `"none"` for CSS spec parity

**Comment by LeaVerou** [comment]
Yeah we resolved to represent `none` as `null`, so that `NaN` can retain its meaning, but I haven't found time to make the change

**Comment by LeaVerou** [comment]
This was fixed recently. 

Several things:
- hTest does deep equality by default (and is also smart about NaN etc) so serializing test output to JSON was never needed. They now simply return objects. This way pass/fail is also independent of property order, and we could do subset testing when needed.
- There was a bug in hTest where it would throw all numbers at `JSON.stringify()`, which caused `NaN` to be serialized as `null`. This has now been fixed ([as of today!](https://github.com/LeaVerou/htest/pull/28))
