### ISSUE TITLE
Color.mix provides different results from CSS native color-mix in oklch space

### ISSUE THREAD

**Issue by zemd** [color-js/color.js#358]
Hey, I'm not sure if this is a bug or not, but I noticed some differences in how the library mixes color for oklch space.

<img width="1509" alt="Screenshot 2023-11-22 at 10 15 28" src="https://github.com/LeaVerou/color.js/assets/433708/5e501fd8-bfcf-4a1a-a5ec-f437b4f190ae">

Source is here: https://codepen.io/dmitry_zelenetskiy/pen/abXGopp

So when the output space is `oklch` the CSS `color-mix` displays it differently from hex values(which is also similar to `lch` output).
But the library doesn't differentiate them and `oklch` results are similar.

**Comment by facelessuser** [comment]
@zemd make sure you are interpolating your colors in `oklch`. The version of color.js that you are using is interpolating in Lab by default. The lightness steps match Lab's lightness response.

You need to compare apples to apples. In your code, you are explicitly interpolating within the OkLCh color space:

```js
`color-mix(in oklch, ${OKLCH_BLACK} ${factor}%, ${OKLCH_WHITE})`
```

`in oklch` isn't setting the output space, it is setting the interpolation space, though the colors will get returned in that space. The colors won't be converted to your display gamut until displayed.

So you need to do the same with Color.js by setting the interpolation color space.

```js
makeGradient(document.querySelector(".g6"), (factor) => {
  const color = new Color(Color.mix(OKLCH_WHITE, OKLCH_BLACK, factor / 100, {space: 'oklch'}));
  return color.to("oklch");
});

makeGradient(document.querySelector(".g7"), (factor) => {
  const color = new Color(Color.mix(OKLCH_WHITE, OKLCH_BLACK, factor / 100, {space: 'oklch'}));
  return color.to("lch");
});
```

And now the results match!

<img width="1673" alt="Screenshot 2023-11-25 at 10 59 34 AM" src="https://github.com/color-js/color.js/assets/1055125/5dbe33d9-e1dc-464c-b5cf-0ec96a2f0952">
