### ISSUE TITLE
New test suite discards description fields

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#363]
Example of the omitted data:

```js
name: "OKLab",
	description: "Conversions tested against results from published linear sRGB to OKLab C++ code (using better matrices, updated 2021-01-2)",
	data: {
		toSpace: "oklab",
	},
```

The [old (html first) test suite](https://colorjs.io/tests/conversions) exposed that description

![image](https://github.com/color-js/color.js/assets/2506926/093ee22b-e854-4698-84ff-ee6911b85f9a)

**Comment by svgeesus** [comment]
Looks like this would need to be fixed in htest [render.js](https://github.com/LeaVerou/htest/blob/main/src/js/render.js) by inserting a new line [here](https://github.com/LeaVerou/htest/blob/807def2987af3e864e9580fe6c06859c70c35f28/src/js/render.js#L28-L30):

```js
  contents: [
        {tag: "h1", textContent: t.name},
        table = create({tag: "table", class: "manual reftest",
```
to test if the description exists and if so, create a paragraph containing the description after the `h1`.

**Comment by LeaVerou** [comment]
Yup. PR?

The line would be something like:

```js
description? {tag: "p", textContent: description } : undefined,
```

**Comment by LeaVerou** [comment]
You should also close this issue here and file it to htest.
