### ISSUE TITLE
Near-blacks in `oklab` crash the convert utility

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#376]
Compare [`oklab(0.002 0 0)`](https://colorjs.io/apps/convert/?color=oklab(0.002%200%200)&precision=6) which has no output at all, with [`oklab(0.00000 0 0)`](https://colorjs.io/apps/convert/?color=oklab(0.00000%200%200)&precision=6) which does

![image](https://github.com/color-js/color.js/assets/2506926/2f009fd6-6b6d-47b3-a437-746888e4f63a)

**Comment by facelessuser** [comment]
This seems true for any value close to zero: [`rgb(0.00001 0.00001 0.00001)`](https://colorjs.io/apps/convert/?color=rgb(0.00001%200.00001%200.00001)&precision=6).

**Comment by facelessuser** [comment]
This failure is due to a bug with an uninitialized value: https://github.com/color-js/color.js/blob/main/src/toGamut.js#L183. 

It should be:

```js
let current = clone(origin_OKLCH)
```

**Comment by facelessuser** [comment]
Actually, it should be:

```
let current = clip(clone(mappingSpace));
```

**Comment by svgeesus** [comment]
Fixed by https://github.com/color-js/color.js/pull/352
