### ISSUE TITLE
toPrecision is broken

### ISSUE THREAD

**Issue by efergus** [color-js/color.js#385]
toPrecision outputs the wrong values for some inputs. The function considers the leading "0" in a decimal number to be a significant digit, which it is not.

For example: The `toPrecision` function is wrong for decimal inputs like `0.222`:

Ex:
```js
toPrecision(0.222, 2) // 0.2
```
Instead, it should be
```js
toPrecision(0.222, 2) // 0.22
```

**Comment by svgeesus** [comment]
Hmm, I have noticed this myself on occasion. Thanks for the PR!
