### ISSUE TITLE
Support for CMYK color spaces

### ISSUE THREAD

**Issue by blunteshwar** [color-js/color.js#387]

**Comment by LeaVerou** [comment]
As explained in https://github.com/color-js/color.js/pull/386#issuecomment-1902237776 this depends on #45 .

Once ICC profiles are supported, we could then add some common CMYK spaces (e.g. US Coated SWOP, FOGRA, etc.) to be available as predefined spaces and decide which one `"cmyk"` should resolve to (if any), though I'm not sure about their licensing requirements. @svgeesus, I’m sure you'd have many thoughts here!

**Comment by svgeesus** [comment]
This is a dup of #45 because there is no single "CMYK color space"
