### ISSUE TITLE
[chore] Port missing Constructor tests

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#394]
There are 5 tests in the old Constructor test suite and 3 in the new suite.

**Comment by lloydk** [comment]
These tests have been ported. I was just looking at the count of tests in the browser and didn't realize there was an issue with htest and the deepest nested tests.

```
Uncaught TypeError: Cannot read properties of undefined (reading 'cells')
    at TestResult.<anonymous> (render.js:70:7)
    at TestResult.dispatchEvent (BubblingEventTarget.js:21:16)
    at TestResult.dispatchEvent (BubblingEventTarget.js:17:12)
    at TestResult.evaluate (TestResult.js:148:8)
    at TestResult.run (TestResult.js:84:8)
    at TestResult.js:126:10
```

Tests that are causing the exception

https://github.com/color-js/color.js/blob/49455aa13071bcc2bc275ede9cb5f0d7e5089de0/test/construct.js#L17-L28

**Comment by LeaVerou** [comment]
Ah yes, the HTML view of these tests is an MVP and only deals with up to a certain level of nesting. The Node runner should work fine though. 
If you can [file a bug](https://github.com/LeaVerou/htest/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) on this so I can track it, that would be very helpful! 
Should I close this?

**Comment by lloydk** [comment]
There are some failing tests

This test fails because of a strict equality check:
https://github.com/color-js/color.js/blob/49455aa13071bcc2bc275ede9cb5f0d7e5089de0/test/construct.js#L35

The test passes if I change === to == here:

https://github.com/LeaVerou/htest/blob/70958deaf9bfd58ecb1f4ce247ffb7a9a3af2608/src/check.js#L43

Two other tests are failing because of alpha is undefined. I'll submit a PR that fixes those two tests sometime today.

**Comment by LeaVerou** [comment]
Thank you!

**Comment by lloydk** [comment]
All of the constructor tests pass so I'm going to close this.
