### ISSUE TITLE
[chore] Port Color modification tests to the new test format

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#395]

**Comment by LeaVerou** [comment]
Hi @lloydk, it would be helpful to link to the part of the testsuite you're referring to. E.g. I thought these had already been ported? See https://github.com/color-js/color.js/blob/main/test/conversions.js

**Comment by lloydk** [comment]
> Hi @lloydk, it would be helpful to link to the part of the testsuite you're referring to. E.g. I thought these had already been ported? See https://github.com/color-js/color.js/blob/main/test/conversions.js

These tests:

https://github.com/color-js/color.js/blob/main/tests/modifications.html
