### ISSUE TITLE
Preparing for v0.5.0 release

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#403]
It has been [embarassingly long](../releases/) since our last release. Lots of complaints that fixes are not on npm yet.

I’m opening this issue to see if there are any last minute items we want to get in before releasing a new version.
Any PRs you want to try and get merged? Any issues you want to try and get resolved first? (easy and quick things please; we don't want to delay the release even more).

If I don't get a response from you by Wednesday, I’ll assume the answer is "no".

Also, any thoughts on what the next version should be? v0.4.6 or v0.5.0? (remember semver works differently for 0.x.y so the "no API changes in minor versions" doesn't apply).

CC @svgeesus @jgerigmeyer @MysteryBlokHed

**Comment by jgerigmeyer** [comment]
Makes sense to me, and I don't have any open PRs/issues I want to squeeze in. I didn't get to it last week, but I'm happy to help with the release process. I can take a look at that tomorrow.

I think my leaning would be v0.5.0 given the number and significance of changes, but I don't feel strongly about it.

**Comment by svgeesus** [comment]
> Any PRs you want to try and get merged? Any issues you want to try and get resolved first?

Not for me; nothing that justifies holding up a release.

**Comment by MysteryBlokHed** [comment]
No PRs/issues from me. I'd also lean towards v0.5.0 for the version, since it's been a while and there have been a good amount of changes.

**Comment by lloydk** [comment]
I'll probably submit a PR for the HSLuv and HPLuv color spaces later tonight or tomorrow. Not sure if you want to wait for those color spaces before issuing a release.

**Comment by LeaVerou** [comment]
> I'll probably submit a PR for the HSLuv and HPLuv color spaces later tonight or tomorrow. Not sure if you want to wait for those color spaces before issuing a release.

Can't hurt! We can list support as experimental in the release notes, since they won't have been tested much.

**Comment by LeaVerou** [comment]
> Makes sense to me, and I don't have any open PRs/issues I want to squeeze in. I didn't get to it last week, but I'm happy to help with the release process. I can take a look at that tomorrow.
> 
> I think my leaning would be v0.5.0 given the number and significance of changes, but I don't feel strongly about it.

That would be amazing, as I’m so incredibly swamped.

**Comment by jgerigmeyer** [comment]
I'll work on preparing a release today. @LeaVerou If you have a chance to take a look at https://github.com/color-js/color.js/pull/407 and https://github.com/color-js/color.js/pull/404, I think we might want to get those in before a release.

**Comment by LeaVerou** [comment]
Will try to take a look tonight. Can you create the changelog as a draft release so I can take a look?

**Comment by jgerigmeyer** [comment]
> Can you create the changelog as a draft release so I can take a look?

@LeaVerou Draft added (and organized a bit): https://github.com/color-js/color.js/releases/tag/untagged-7d69a8cfc48478b3d420

**Comment by jgerigmeyer** [comment]
@LeaVerou All PRs are merged now -- should I go ahead with a release, and if so do you prefer beta or direct to v0.5.0?

**Comment by lloydk** [comment]
I think #408 should be dealt with before doing a release.

**Comment by lloydk** [comment]
> I think #408 should be dealt with before doing a release.

Nevermind, turns out it wasn't an issue.

**Comment by LeaVerou** [comment]
Thank you so much @jgerigmeyer for getting this started. I made a pass and made several edits. Some high level feedback that may help for the future is:

- We don't need to faithfully replicate PR titles, it's more important that the changelog reads like a list of changes
- Wording should focus around the value proposition for users, not the low level implementation details

This still needs some work, so I suggest holding off for a bit more.

**Comment by svgeesus** [comment]
Is it worth mentioning in the release notes that we _didn't_ add dashed ident for `rec2100-hlg`, `rec2100-pq`, `Jzazbz`, `JzCzHz` and `ICtCp` because, while these are not in CSS Color 4, they _are_ in the recently-adopted [CSS Color HDR](https://drafts.csswg.org/css-color-hdr/)?

**Comment by LeaVerou** [comment]
Ugh, do *not* hit Cmd+Enter when editing a draft release! I just did that and accidentally published the release!! 🤦🏽‍♀️🤦🏽‍♀️🤦🏽‍♀️
I had to delete it and create a new draft, since there’s no way to return a release to draft mode 🤦🏽‍♀️
Did you get an email?

**Comment by jgerigmeyer** [comment]
> Did you get an email?

I didn't get an email or notification, and I'm watching "All Activity" on this repo.

**Comment by LeaVerou** [comment]
> > Did you get an email?
> 
> I didn't get an email or notification, and I'm watching "All Activity" on this repo.

Interesting. I did.

**Comment by svgeesus** [comment]
So, are we merging

 - https://github.com/color-js/color.js/pull/420

before release?

**Comment by svgeesus** [comment]
HCT is now merged!

**Comment by svgeesus** [comment]
So we are blocked on solving

 - https://github.com/color-js/color.js/issues/433

**Comment by lloydk** [comment]
> So we are blocked on solving
> 
> * [REGRESSION: (Some) nonstandard color spaces error when round-tripping #433](https://github.com/color-js/color.js/issues/433)

See my comment: https://github.com/color-js/color.js/issues/433#issuecomment-1942996302

The PR doesn't allow for parsing both dashed and non-dashed id as suggested in the issue. If we want to support dashed and non-dashed ids then more work needs to be done.

**Comment by LeaVerou** [comment]
Thanks for working on this @lloydk! I left a comment in the PR, but if this issue is present in the previous release as well, then it's not a blocker.

**Comment by jgerigmeyer** [comment]
It would be good to get #439 (or a version of it) merged, but then I think this is ready for at least an alpha/beta release?

**Comment by facelessuser** [comment]
I agree. If color.js is serializing a color to a specific format, it should be able to parse it as well. #439 (or some equivalent fix) seems important enough to wait for.

**Comment by svgeesus** [comment]
So, https://github.com/color-js/color.js/pull/439 is merged.

**Comment by jgerigmeyer** [comment]
> So, https://github.com/color-js/color.js/pull/439 is merged.

Draft release notes are updated, local testing today revealed https://github.com/color-js/color.js/pull/466 which I was hoping we could merge before release if @MysteryBlokHed or someone else could review.

**Comment by jgerigmeyer** [comment]
https://github.com/color-js/color.js/pull/466 is merged, I'll release v0.5.0 tonight unless someone else beats me to it or raises a blocking issue.

**Comment by lloydk** [comment]
Do we want to resolve #442 before doing a release?

**Comment by jgerigmeyer** [comment]
> Do we want to resolve #442 before doing a release?

@lloydk I think #442 is a good addition, but I don't view it as a blocker for v0.5.0.
