### ISSUE TITLE
Use <dashed-ident> for CAM16-JMh and HCT

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#405]
According to [this issue](https://github.com/color-js/color.js/issues/178) color spaces that aren't part the CSS spec should be using a dashed-ident.

CAM16-JMh and HCT haven't been part of an official release so it's probably safe to change to a dashed-ident before doing a release.

**Comment by LeaVerou** [comment]
I’m tending to agree. We should probably parse `<dashed-ident>` versions of native color spaces too in Color.js; this ensures that if a color space is "upgraded" to native, existing code continues to work.

@facelessuser @svgeesus thoughts?
