### ISSUE TITLE
CSS gamut mapping method gives incorrect results

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#408]
Example color is `lch(40.383 143.28 272.5)` which should have a blueish hue.

### CSS Gamut mapping
https://colorjs.io/apps/convert/?color=lch(40.383%20143.28%20272.5)&precision=4
![image](https://github.com/color-js/color.js/assets/65072/00450a8d-3d6c-4370-9305-90a3d0ca757b)

### Gamut mapping using lch.c
![image](https://github.com/color-js/color.js/assets/65072/44882bb5-6250-4646-adb0-7060574957a2)

Coloraide gamut mapping using 'oklch-chroma'
![image](https://github.com/color-js/color.js/assets/65072/81412472-ff60-441b-9cfa-4960421cab76)

**Comment by lloydk** [comment]
I think this is just a result of the weird shape of the OKLCH color space for imaginary colors in the blueish hue range. I had assumed that converting `lch(40.383 143.28 272.5)` to `oklch` would result in an imaginary `oklch` color with the same hue. So I think this can be closed.

**Comment by facelessuser** [comment]
I see you are using ColorAide as an example. Keep in mind a couple of things:

You didn't specify a gamut, so no gamut mapping occurred when you used `oklch-chroma` as LCh has no defined gamut. Then when we went to display it on the site, we determined the color was still out of gamut (indicated by the pink border) and we used the default gamut mapping method which is still LCh. [Here](https://facelessuser.github.io/coloraide/playground/?code=Color%28%27lch%2840%2e383%20143%2e28%20272%2e5%29%27%29%2efit%28%27srgb%27%2C%20method%3D%27oklch-chroma%27%29%0AColor%28%27lch%2840%2e383%20143%2e28%20272%2e5%29%27%29%2efit%28%27srgb%27%2C%20method%3D%27lch-chroma%27%29) are actual results when comparing between LCh and OkLCh gamut mapping using the same color.

<img width="1335" alt="Screenshot 2024-02-09 at 7 02 22 AM" src="https://github.com/color-js/color.js/assets/1055125/fcc1b372-84e0-4325-b276-103676d6a20f">

If the color is quite extreme in the bluish region, OkLCh kind of breaks down once you are out of the visible gamut. It's one of the reasons I still default to LCh gamut mapping even if OkLCh does better in many instances. LCh doesn't handle certain regions perfectly (purple shift in blue region), but the shape of LCh in extreme gamuts gives more sane results generally. I think it ends up being less surprising generally. I still think OkLCh does better when the colors are not so extreme, I just think you have to use it in situations where OKLCh doesn't break down.

I've posted this before, but we can see this when OkLCh is rendered in the [ProPhoto gamut](https://facelessuser.github.io/coloraide/demos/3d_models.html?space=oklch&gamut=prophoto-rgb&edges=false&aspect=false&ortho=false).

![oklch-prophoto](https://github.com/color-js/color.js/assets/1055125/281884b2-03c8-4f5b-adb8-f442e5310751)

To illustrate why the algorithm fails, let's try visualizing it by gamut mapping `lch(40.383 143.28 272.5)` in ProPhoto.  There's no reliable way to gamut map these situations.

![oklch-prophto-gamutmap](https://github.com/color-js/color.js/assets/1055125/36610747-95cb-4b74-9c4c-a9005619fc9b).

Some Lab color spaces, while not having a defined gamut, can still have reasonable limits. Even spaces like [CAM16 can break down](https://facelessuser.github.io/coloraide/demos/3d_models.html?space=cam16-jmh&gamut=prophoto-rgb&edges=false&aspect=false&ortho=false) if they are rendered in a large enough gamut. Notice blue twisting back into the color solid.

![cam16-prophoto](https://github.com/color-js/color.js/assets/1055125/1ac46918-f501-4d2b-b886-f1d6b9d52ef7)

**Comment by lloydk** [comment]
Thanks for the explanation. I think I may end up gamut mapping using LCh for the color spaces where the results look really broken.

At any rate this isn't an issue so I'm gonna close it.

**Comment by facelessuser** [comment]
That makes sense. If you are using ColorAide as a comparison, it might not always match what Color.js generates as I use LCh with a D65 white point for gamut mapping and Color.js uses D50. Just an FYI.
