### ISSUE TITLE
[apps/picker] App is broken

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#411]
It appears that commit 35a6ac50199105e306a8cf0eae339fd277815de0 broke the picker app. 

Nothing works and I’m getting this:
<img width="394" alt="image" src="https://github.com/color-js/color.js/assets/175836/b168eea0-c7e0-48c7-b52e-0c3b88013059">

I don’t understand why, since it's such a small change and seems totally fine! @sidewayss any thoughts?

**Comment by LeaVerou** [comment]
Ah, I see it now. It’s a missing quote!

**Comment by sidewayss** [comment]
As I said, only semi-educated.  Glad it wasn't more serious!
