### ISSUE TITLE
Discord server for Color.js

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#412]
As our core maintainer team grows, we need some kind of more immediate/transient communication than GitHub issues, and also the ability to discuss things privately (e.g. I wanted to propose we invite someone as a new maintainer and it was entirely nontrivial to do so).

Color.js users may also benefit from something like this (we have the [Discussions](https://github.com/color-js/color.js/discussions) section but it's not used much).

I was considering of setting up a Discord server, what do others think? @svgeesus @jgerigmeyer @MysteryBlokHed 
Assuming you’re ok with it, could you either post your Discord usernames here or (for privacy) email them to me? (it's `[my first name]` @ `[my last name]` .me)

**Comment by MysteryBlokHed** [comment]
A Discord server sounds good to me! My username is the same as on GitHub, `@mysteryblokhed`

**Comment by jgerigmeyer** [comment]
Works for me -- `jgerigmeyer` 👍

**Comment by svgeesus** [comment]
Nantonos

**Comment by LeaVerou** [comment]
Could someone add something on the website about the Discord server?

**Comment by LeaVerou** [comment]
Since that has happened as well, I’m now closing this.
