### ISSUE TITLE
[chore] Use typedoc for API docs

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#424]
Our `/api` docs are currently a total mess because they are not being updated. Instead, the only docs we really have are those under `/docs`. We also need proper low level API docs.

I’ve recently started using typedoc in other projects and it seems to work better than any of the others I’ve tried from time to time.

**Comment by MysteryBlokHed** [comment]
Before switching over, more detailed doc comments should probably be added to the types since many functions/properties are undocumented. The docs could probably just be copy+pasted from the current API page for the most part

**Comment by LeaVerou** [comment]
Just pushed a first stab at this, since our API docs were preposterous. Lots of room for improvement though if someone wants to experiment with the settings!
