### ISSUE TITLE
(Some) nonstandard color spaces error when round-tripping

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#433]
~**This is a blocker for v0.5.0 as it's a pretty serious regression**~ Turns out this exists in v0.4.3 too 🤦🏽‍♀️

Try this in the console:
```
new Color(new Color("red").to("p3-linear").toString())
```

<img width="567" alt="image" src="https://github.com/color-js/color.js/assets/175836/6755aedb-057c-4098-8c8d-66df783134e5">

**Comment by LeaVerou** [comment]
I think we should parse both forms in v0.5.0 to ease the transition, and just print out a warning when using unprefixed ids for nonstandard spaces.

**Comment by lloydk** [comment]
I don't think this is a regression but a case of missing formats. I tested the 0.45 and 0.43 releases and had the same problem.

I created a PR for the missing formats #435.

**Comment by LeaVerou** [comment]
Thanks for working on this @lloydk! I left a comment in the PR, but if this issue is present in the previous release as well, then it's not a blocker.

**Comment by jgerigmeyer** [comment]
I proposed a slightly larger fix for this in #439.
