### ISSUE TITLE
Support `rec2100-linear`?

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#443]
I wonder if we should support [`rec2100-linear`](https://drafts.csswg.org/css-color-hdr/#valdef-color-rec2100-linear) from CSS Color HDR. It was  [requested](https://github.com/w3c/csswg-drafts/issues/553#issuecomment-1809200438) by the Color on the Web CG, primarily for Canvas, and adopted by [CSSWG resolution](https://github.com/w3c/csswg-drafts/issues/553#issuecomment-1864865513).

Although it is an HDR space, it is defined with `white` === `color(rec2100-linear 1 1 1)` (so the actual HDR values are above 1). That makes it an **exact alias** of `color(--rec2020-linear)`, because BT.2100 uses the BT.2020 primaries and white point, differing only in the transfer function.

**Comment by LeaVerou** [comment]
I think we should generally aim to support a linear version of every RGB color space.
