### ISSUE TITLE
Scientific notation causes error in OKLCH?

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#509]
### Discussed in https://github.com/color-js/color.js/discussions/507

<div type='discussions-op-text'>

<sup>Originally posted by **maybebansky** April 26, 2024</sup>
I'm using scientific notation for color channels that I pass to the Color object in the OKLCH format. 

I know it's a bit weird but I'm getting these values as a result of color manipulation elsewhere in my app. 

```
// This works fine
const color1 = new Color("oklch(50% 4 30)");

// This errors
const color2 = new Color("oklch(50% 4.0e-1 30)");
```
`"oklch(50% 4.0e-1 30)"` does appear to be valid CSS so is this technically a bug (albeit it an edge case)? 

The error is

```
Uncaught TypeError: undefined not allowed for Chroma in oklch()
```

</div>

**Comment by svgeesus** [comment]
So, fixed due to https://github.com/color-js/color.js/pull/508 ?

**Comment by facelessuser** [comment]
Yes. This is now fixed.
