### ISSUE TITLE
OkHSL/OkHSV does not use NaN for hue-less colors

### ISSUE THREAD

**Issue by KeyboardDanni** [color-js/color.js#516]
The OkHSL/OkHSV spaces do not seem to use NaN for hue in their conversions, unlike other colorspaces such as HSL/HSV and LCH/OkLCH. One side effect of this is that interpolation from srgb(0.0, 0.0, 1.0) to srgb(1.0, 1.0, 1.0) produces incorrect results:

![2024-05-16 15_03_29-Palettejuicer](https://github.com/color-js/color.js/assets/34800072/8d9262f0-60c1-42aa-9c34-6f8a8b65c159)

The top strip is lerping over OkLCH, and the middle and bottom ones are using OkHSV and OkHSL, respectively. Because srgb(1.0, 1.0, 1.0) isn't converting to a hue of NaN, OkHSV and OkHSL are incorrectly blending their hues toward 0.

Reproduction:

```js
const white = { space: "srgb", coords: [1.0, 1.0, 1.0] };

const whiteOklch = to(white, "oklch"); // [ 1.0000000000000002, 4.996003610813204e-16, NaN ]
const whiteOkhsl = to(white, "okhsl"); // [ 180, 0.6519721306444567, 1.0000000000000002 ]
const whiteOkhsv = to(white, "okhsv"); // [ 180, 1.3189507366749435e-15, 1.0000000000000007 ]
```

**Comment by facelessuser** [comment]
Ugh, that was my fault as I implemented the spaces. I'll get a fix up.

**Comment by facelessuser** [comment]
I've linked a PR that should fix the issue.

**Comment by svgeesus** [comment]
Fixed by https://github.com/facelessuser/color.js/commit/af37eb5c6cf79682f628bb0fc70eba154a55634a

**Comment by KeyboardDanni** [comment]
Too soon to close? That's the upstream, which doesn't seem to have been merged yet.

**Comment by LeaVerou** [comment]
Nah, we close when fixes are merged, not when the version with them is released.
