### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by apparebit** [color-js/color.js#531]
For a while now, I've had some ideas about making color management for terminals more web-like. I had even built a prototype but used very gnarly ad-hoc color conversions. A few weeks ago, I started looking at Color.js and realized that, not only were all the features I needed right there, but the code was so exceptionally well structured that porting over to Python would be real easy. It's about two plus weeks later and I just released the first usable version of [prettypretty](https://github.com/apparebit/prettypretty), which combines 1970s terminals with 2020s applied color science for much nicer terminal colors. The low-level conversions between color spaces are all based on Color.js, which was just the right foundation to get me going. I implemented gamut mapping based on the CSS spec, which was super clear as well—I'm guessing also thanks to you. I acknowledge the heritage on the main documentation page. But if you prefer a different placement or wording, just let me know. Thank you for making color algorithms accessible!

**Comment by svgeesus** [comment]
The attribution is appreciated, thank you! Glad color.js was helpful.
