### ISSUE TITLE
[`getAll`] Add an option(?) so that formatted coords can be returned

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/color.js#542]
This idea initially came from the need to [show coords in a color swatch](https://github.com/color-js/elements/issues/81) formatted as they are in the parsed color. Something like this:

<img width="200" alt="image" src="https://github.com/color-js/color.js/assets/9166277/8c3fb0c6-2232-4411-9f93-53b6d0a4a6ae">

@LeaVerou [pointed out](https://github.com/color-js/elements/pull/93#issuecomment-2158248994) that, unfortunately, there is no way to do it now, but it might be a good feature of `getAll()`.

So, I'm filing this issue to request this feature. 🙃

**Comment by LeaVerou** [comment]
Low hanging fruit would be to add `precision`, we could also add `type` which would serialize to `<angle>` or `<percentage>`.
