### ISSUE TITLE
Incorrect serialization of negative values for sRGB and HSL

### ISSUE THREAD

**Issue by lloydk** [color-js/color.js#552]
Negative values are serialized as `-Infinity`.

https://apps.colorjs.io/convert/?color=oklch(0%2C%200.1%2C%20180)&precision=4

![image](https://github.com/color-js/color.js/assets/65072/acf0674c-8f0d-46eb-a480-165c7ed38ee2)

**Comment by lloydk** [comment]
Or `NaN` in this case.

https://apps.colorjs.io/convert/?color=rgb(-0.00001%200%200)&precision=4
![image](https://github.com/color-js/color.js/assets/65072/a41bc28a-b44e-4ba8-bcfb-29c2ca7c91ca)

**Comment by LeaVerou** [comment]
Is this a regression?

**Comment by LeaVerou** [comment]
We should have tests on thus

**Comment by facelessuser** [comment]
It's likely a regression, I don't recall behavior like this in the past.

**Comment by LeaVerou** [comment]
@DmitrySharabin could you test if this behavior is present in v0.5.0 and add some tests for it? Thanks!

**Comment by lloydk** [comment]
It's a regression. Here are the result for v0.5.0:

![image](https://github.com/color-js/color.js/assets/65072/c563dfb5-9178-417d-a148-cf8ecccf7c5e)

**Comment by lloydk** [comment]
I took a quick look at this with the following tests:

```js
		{
			name: "Negative percentages",
			skip: false,
			tests: [
				{
					name: "sRGB - inGamut: false",
					args: ["srgb", [-0.1, 0, 0], 1, {inGamut: false}],
					expect: "rgb(-0.1% 0% 0%)",
				},
				{
					name: "sRGB - inGamut: true",
					args: ["srgb", [-0.1, 0, 0], 1, {inGamut: true}],
					expect: "rgb(0% 0% 0%)",
				},
				{
					name: "oklab - inGamut: false",
					args: ["oklab", [-0.29147106051849636, -0.1044, -0.0584], 1, {inGamut: false}],
					expect: "oklab(-0.29147 -0.1044 -0.0584)",
				},
				{
					name: "oklab - inGamut: true",
					args: ["oklab", [-0.29147106051849636, -0.1044, -0.0584], 1, {inGamut: true}],
					expect: "oklab(-0.29147 -0.1044 -0.0584)",
				},
			],
		},
```
and some log statements in the `Type.serialize()` and `util.mapRange()` functions

![image](https://github.com/color-js/color.js/assets/65072/93a1cfdc-e0b4-452d-b7ed-f60ad7640924)

Looks like mapping a negative value from 0,1 to -100,100 is causing the issue. That's as far as I got, I'm heading out for the evening.

**Comment by lloydk** [comment]
I think I have a fix for this issue, I'll create a PR in the morning.

**Comment by LeaVerou** [comment]
Thanks @lloydk! Can you commit these tests? (if you haven't already)
