### ISSUE TITLE
Incompatible with `typescript@5.5.2`

### ISSUE THREAD

**Issue by jlarmstrongiv** [color-js/color.js#560]
Reproduction https://github.com/jlarmstrongiv/colorjsio-ts

<img width="505" alt="image" src="https://github.com/color-js/color.js/assets/20903247/8b0e91e6-9d89-466b-ae01-7e63f4ee4839">

**Comment by LeaVerou** [comment]
Hi @jlarmstrongiv, is this about the dev branch or the currently released v0.5.0?

**Comment by jlarmstrongiv** [comment]
@LeaVerou this issue is about `colorjs.io@0.5.0` with `typescript@5.5.2`

**Comment by LeaVerou** [comment]
Ah okay. We've made some major changes wrt typing in v0.6.0 and we’re still not done. We’ll do an alpha soon, please check it out to see if you still have this issue?

**Comment by jlarmstrongiv** [comment]
Sure 👍 Let me know when you make an alpha release of v0.6.0 or a patch release of 0.5.1 and I’ll give it a go

**Comment by MysteryBlokHed** [comment]
@jlarmstrongiv Could you check whether this error still happens on v0.5.2?

**Comment by jlarmstrongiv** [comment]
@MysteryBlokHed thank you!  I can confirm the error is resolved on v0.5.2 👍
