### ISSUE TITLE
should add an isNaN() method

### ISSUE THREAD

**Issue by BonesYT** [color-js/color.js#562]
There should be a built-in "isNaN()" method to check if any of the color space values are invalid, just a basic function

**Comment by LeaVerou** [comment]
There…is? Two in fact: [`isNaN()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) and [`Number.isNaN()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN)

**Comment by LeaVerou** [comment]
I’m gonna go ahead and close this, but if I minderstood what you were proposing, feel free to reopen!
