### ISSUE TITLE
[types] Generate declarations from JS

### ISSUE THREAD

**Issue by MysteryBlokHed** [color-js/color.js#563]
Created a separate issue to move discussion away from #555.

Adding the following options to the root `tsconfig.json` allows declaration files to be generated from JS:

```json
"declaration": true,
"emitDeclarationOnly": true
```

The only concern I have is that it clogs up the repository with many `.d.ts` files, which shouldn't be committed. This can be partially solved with `.gitignore` (and then adding exceptions for the `.d.ts` files that _are_ meant to be there), but it's still kind of annoying as a developer.

I tried changing the `outDir` option to put the declaration files into their own directory (like they used to be before the JSDoc migration), but it doesn't seem to copy over the `.d.ts` source files (like `index.d.ts`).

**Comment by lloydk** [comment]
What if we copied the non-generated .d.ts files to the outDir?

**Comment by MysteryBlokHed** [comment]
That'd work...not sure why that wasn't an immediate thought of mine 😅

I'll start working on a PR to generate declarations. I think it'd be best to `.gitignore` all the definitions files and have a script to generate + copy files on release.
