### ISSUE TITLE
An unnecessary full style recalculation is done every scroll event on many pages of `colorjs.io`

### ISSUE THREAD

**Issue by Inwerpsel** [color-js/color.js#587]
When checking dev tools for the site, I noticed that every scroll event the `--scrolltop` custom property of the `html` element is updated.

While at a glance this might not look expensive, it actually results in a style recalculation of all elements on the page. I'm pretty sure it's the only reason the scrolling is choppy, and removing this property update is enough to make the page scroll normally.
<details>
<summary><h3>Performance recording during scrolling</h3></summary>

<img src='https://github.com/user-attachments/assets/6415686a-21cc-4d6e-86d1-4f87988561e6' id='perf-during-scroll' />

Details of a single recalc, taking 25.18ms on desktop.

![colorjs-scrolling-recalc-detail](https://github.com/user-attachments/assets/794c40f3-d7b2-443f-900a-0a2ad971455c)

</details>

This is triggered by an event listener that only sets a custom property on the root element.

https://github.com/color-js/color.js/blob/f50d95a542b6a487d0ffdd004b62879f200c148d/assets/js/index.js#L16-L18

The only reference to this custom property is in the `#toc` element, where it's used to move a `position: fixed` element depending on the scroll position.

https://github.com/color-js/color.js/blob/f50d95a542b6a487d0ffdd004b62879f200c148d/assets/css/docs.css#L13-L24

It looks a lot like this CSS can be replaced with `position: sticky`, completely removing the need to update the root property and thereby removing all the time spent on the purple stuff in above graphs.

**Comment by svgeesus** [comment]
Scrolling is indeed choppy; feel free to send a pull request!

**Comment by Inwerpsel** [comment]
I created a second PR with a much simpler solution that should have no risk and still get us a similar performance improvement by reducing the scope of the recalculation.
