### ISSUE TITLE
Color constructor should handle argument as immutable

### ISSUE THREAD

**Issue by bennyschudel** [color-js/color.js#590]
Hey there!

I was surprised to figure out that a call to `new Color({ ... })` modifies my provided object by adding the `space` to it.

<img width="570" alt="image" src="https://github.com/user-attachments/assets/b63049d2-c3fc-4793-bd12-364b3c5d149a">

I guess this is a 🪲

Best
Benny

**Comment by LeaVerou** [comment]
Ah yeah, it should copy the object, at least when it needs to be modified. Especially since perf is not a huge consideration with the OOP API.

**Comment by MysteryBlokHed** [comment]
It looks like `getColor` modifies the passed object, adding the `space` key:

<https://github.com/color-js/color.js/blob/45ba17298a8655befa2e22f6d7581e159a70fc53/src/getColor.js#L40-L43>

This could be solved by calling `structuredClone` before `getColor` in the Color constructor:

<https://github.com/color-js/color.js/blob/45ba17298a8655befa2e22f6d7581e159a70fc53/src/color.js#L48-L56>


i.e.:

```javascript
color = getColor(structuredClone(args[0]), {parseMeta});
```

**Comment by LeaVerou** [comment]
This is by design, `getColor` needs to be **fast** so it should avoid creating objects. We can absolutely fix this in the OOP API, but I think it would slow things down for the procedural API.

**Comment by LeaVerou** [comment]
Not sure we need `structuredClone()`, as this is a flat object, so `Object.assign({}, ...)` should work?

**Comment by MysteryBlokHed** [comment]
`Object.assign` wouldn't work on Color class instances that get passed afaik, which is why I suggested `structuredClone`. But after looking at the code, I don't think there's actually a way for a Color instance to have its `space` property mutated by `getColor` (since the function only adds the `space` property if it is missing, and Color instances always have that property). So we could probably just do `Object.assign` if the passed argument is an object, and leave other inputs alone?

**Comment by LeaVerou** [comment]
We can detect if something is a plan object and branch accordingly. Not sure if that would be the best course of action, just throwing it out there as an option.

**Comment by MysteryBlokHed** [comment]
That seems like the most performant thing to do—although I don't actually know the best way to check if something is a plain object in JS. Maybe `args[0].constructor === Object`? Or we could also just check if it's not an instance of Color.

**Comment by LeaVerou** [comment]
> That seems like the most performant thing to do—although I don't actually know the best way to check if something is a plain object in JS. Maybe `args[0].constructor === Object`? Or we could also just check if it's not an instance of Color.

This is how I did it in the past: https://github.com/mavoweb/mavo/blob/main/src/util.js#L61 (`$.type()` just checks `Object.protoyype.toString.call()`, we must have a similar util here)

**Comment by MysteryBlokHed** [comment]
Based on that, I think something like `typeof args[0] === 'object' && Object.getPrototypeOf(args[0]).constructor === Object` should work.
I should be able to open a PR for the change this evening
